# Generated by Django 4.2 on 2025-09-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioPaila',
            fields=[
                ('paila', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('diametro', models.FloatField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('capacidad_planificable', models.FloatField(blank=True, null=True)),
                ('capacidad_total', models.FloatField(blank=True, null=True)),
                ('tara', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('Tipo', models.CharField(max_length=50)),
                ('proceso', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('empastado', models.BooleanField(default=False)),
                ('molino', models.BooleanField(default=False)),
                ('emulsion', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
                ('matizado', models.BooleanField(default=False)),
                ('calidad', models.BooleanField(default=False)),
                ('envasado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Throughput',
            fields=[
                ('primario', models.IntegerField(primary_key=True, serialize=False)),
                ('linea', models.CharField(max_length=50)),
                ('halb', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('pdp', models.FloatField(blank=True, null=True)),
                ('empastado', models.FloatField(blank=True, null=True)),
                ('molino', models.FloatField(blank=True, null=True)),
                ('matizado', models.FloatField(blank=True, null=True)),
                ('emulsion', models.FloatField(blank=True, null=True)),
                ('completado', models.FloatField(blank=True, null=True)),
                ('envasado', models.FloatField(blank=True, null=True)),
                ('fert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.producto')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=100)),
                ('lote_f', models.FloatField(blank=True, null=True)),
                ('estacion', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_inicial', models.DateTimeField(blank=True, null=True)),
                ('hora_final', models.DateTimeField(blank=True, null=True)),
                ('duracion_total', models.FloatField(blank=True, null=True)),
                ('empastado', models.FloatField(blank=True, null=True)),
                ('molino', models.FloatField(blank=True, null=True)),
                ('emulsion', models.FloatField(blank=True, null=True)),
                ('completado', models.FloatField(blank=True, null=True)),
                ('matizado', models.FloatField(blank=True, null=True)),
                ('envasado', models.FloatField(blank=True, null=True)),
                ('fert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.producto')),
                ('paila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.inventariopaila')),
            ],
        ),
        migrations.CreateModel(
            name='PailaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('lavado', 'Pendiente de lavado')], max_length=50)),
                ('paila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.inventariopaila')),
                ('programa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='App.programaproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('primario', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('capacidad_total', models.FloatField(blank=True, null=True)),
                ('relacion', models.FloatField(blank=True, null=True)),
                ('diamsi', models.CharField(blank=True, max_length=10, null=True)),
                ('base_dispersion_minimo', models.FloatField(blank=True, null=True)),
                ('capacidad_planificable', models.FloatField(blank=True, null=True)),
                ('estacion', models.CharField(blank=True, max_length=100, null=True)),
                ('validacion', models.FloatField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.color')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.equipo')),
                ('paila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.inventariopaila')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('primario', models.IntegerField(primary_key=True, serialize=False)),
                ('halb', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.color')),
                ('fert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.producto')),
            ],
        ),
    ]
