# Generated by Django 4.2 on 2025-09-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='App.programaproduccion')),
            ],
        ),
    ]
