# Generated by Django 4.2 on 2025-09-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_programaproduccion_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaproduccion',
            name='produccion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
